# Generated by Django 5.1.4 on 2025-01-04 01:45

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.datetime(2025, 1, 1, 1, 45, 16, 703257, tzinfo=datetime.timezone.utc))),
                ('origin', models.CharField(choices=[('SALARIO', 'Salário'), ('OUTRO', 'Outro')], default='SALARIO', max_length=10)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'indexes': [models.Index(fields=['value', 'date'], name='money_incom_value_ba3af1_idx')],
            },
        ),
    ]
