# Generated by Django 5.1.4 on 2025-01-04 02:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 2, 0, 21, 530092, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(default=datetime.datetime(2025, 1, 4, 2, 0, 21, 530900, tzinfo=datetime.timezone.utc))),
                ('pay', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'indexes': [models.Index(fields=['value', 'due_date'], name='money_payme_value_e7ebf0_idx')],
            },
        ),
    ]
