# Generated by Django 5.1.4 on 2025-01-04 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_income_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 2, 2, 5, 70435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 2, 2, 5, 71769, tzinfo=datetime.timezone.utc)),
        ),
    ]
