# Generated by Django 5.1.4 on 2025-01-04 02:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_alter_income_date_alter_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 2, 3, 6, 173868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
