# Generated by Django 5.1.4 on 2025-01-04 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_income_date_alter_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 2, 7, 50, 369912, tzinfo=datetime.timezone.utc)),
        ),
    ]
