# Generated by Django 5.1.4 on 2025-01-18 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_payment_payment_date_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default='lorem', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 18, 39, 3, 445230, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
