name: Migrate Database on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  run_migrations:
    name: Run Migrations
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.10' # ou a versão que você está usando

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: core.settings
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
